spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/api/v1/profile/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth/**
        - id: wallet-service
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/api/v1/wallet/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - POST
            - GET
            - PUT

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9002/eureka
  instance:
    hostname: localhost
server:
  port: 9090
