server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fyppaymentdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
  application:
    name: PAYMENT-SERVICE

logging:
  level:
    org:
      hibernate:
        type: trace

security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyd4JU7DCqoGMzQHl70yb
          IOp6fsTm00GI9XvyC8VT+8QzS2AvrjeB//DrT+oWIrGviX/trhlmetmwco+9RwDu
          pCsdjyuMbE2RHdMWj5Gx8gs2qrIYIuwxiDjhKtOMOEQnkQ7bCbGJ/awFAUn37QGs
          61v/KN1H3763vAPj7zb04br+AmhmruGU2bsjZAt3R0fY8vwtC014eCtPU52GIHVg
          VPAxf1z2lWC4cGTUq5e7Z4X0e0UPo3EI9C43WNZUc/IOYYaHoncHYNOXUfESeE1j
          BtmnkX4wXdEunTnIgbZiWOp9UbTHE82Aui3lE1qj9pOvZxa9z888R61dUhbYlX9E
          LQIDAQAB
          -----END PUBLIC KEY-----
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9002/eureka
  instance:
    hostname: localhost
