eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9002/eureka
#  server:
#    enable-self-preservation: false
server:
  port: 9002

spring:
  main:
    banner-mode: log
